name: Node.js build and lint

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [26.x]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Install dependencies.
        run: pnpm install
      - name: Build
        run: pnpm run build --if-present
      - name: Lint
        run: pnpm run lint
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            main.js
            manifest.json
            styles.css
