name: Release for Better Headings

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  call-build-and-lint:
    uses: ./.github/workflows/build_and_lint.yaml
  create-release:
    runs-on: ubuntu-latest
    needs: call-build-and-lint
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-output
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css
      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: |
            main.js
            mainifest.json
            styles.css
